version: '3'

services:
  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    depends_on:
      - prometheus
      - fluent_alerter
    volumes:
      - ./prometheus:/etc/alertmanager/
    command:
      - '--config.file=/etc/alertmanager/alertmanager.yml'
  prometheus:
    image: prom/prometheus:v2.21.0
    ports:
      - 9000:9090
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus-data:/prometheus
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml
  fluent_collector:
    image: fluent/fluentd:v1.10-1
    volumes:
      - ./config/fluentd_collector.conf:/fluentd/etc/fluent.conf
      - logs:/opt/logs/:ro
  fluent_alerter:
    image: fluent/fluentd:v1.10-1
    ports:
      - 9880:9880
    volumes:
      - ./config/fluentd_alerter.conf:/fluentd/etc/fluent.conf
      - logs:/opt/logs/:ro
  logstash:
    build:
      context: .
      dockerfile: logstash.Dockerfile
      args:
        buildno: 1
    ports:
      - 9600:9600
      - 5044:5044
    volumes:
      - logs:/opt/logs/:ro
  grok_exporter:
    image: magentaaps/grok_exporter:latest-rc
    command: -config /opt/grok_exporter.conf
    ports:
      - 9144:9144
    volumes:
      - ./config/grok_exporter.conf:/opt/grok_exporter.conf
  apache:
    image: httpd:2.4
    ports:
      - 80:80
    volumes:
      - ./config/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - logs:/usr/local/apache2/logs
  # for debugging purposes:
  echo_server:
    image: ealen/echo-server:0.5.0
    environment:
      PORT: 9145
    ports:
      - 9145:9145

volumes:
  prometheus-data:
  logs:
