http.host: "0.0.0.0"
# xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]

log.level: info
config.debug: false

xpack.monitoring.enabled: false

path.config: /usr/share/logstash/pipeline